### ISSUE TITLE
Clipper doesn't work anymore in qgis 2.6.1

### ISSUE THREAD

**Issue by GlaDal** [demarcog/Clipper#2]
Traceback (most recent call last):
  File "C:/.../.qgis2/python/plugins\clipper\clipper.py", line 193, in run
    self.clip()
 File "C:/.../.qgis2/python/plugins\clipper\clipper.py", line 124, in clip
    diff.setGeometry(g.geometry().difference(fsel.geometry()))
TypeError: QgsFeature.setGeometry(QgsGeometry): argument 1 has unexpected type 'NoneType'

Version de Python :
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

Version de QGIS :
2.6.1-Brighton Brighton, e2a51df

**Comment by GlaDal** [comment]
Right ! I'll will check again (if possible with the same example used before).

Thanks

Bye

**Comment by shetie** [comment]
clipper doesn't work any more
I tried to clip raster image masking with vector data but the clipper gives the following message.Would you please help me. I'm doing in qgis 2.6.1
An error has occured while executing Python code:


Traceback (most recent call last):
  File "C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins\GdalTools\tools\extentSelector.py", line 114, in fillCoords
    self.blockSignals(True)
RuntimeError: wrapped C/C++ object of type GdalToolsExtentSelector has been deleted


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.6.1-Brighton Brighton, e2a51df

Python path: ['C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins\\processing', 'C:/PROGRA~1/QGISBR~1/apps/qgis/./python', u'C:/Users/Administrator/.qgis2/python', u'C:/Users/Administrator/.qgis2/python/plugins', 'C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\Program Files (x86)\\ArcGIS\\bin', 'C:\\PROGRA~1\\QGISBR~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISBR~1\\bin', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', 'C:\\Users\\Administrator\\.qgis2\\python\\plugins\\FeatureGridCreator', 'C:\\Users\\Administrator\\.qgis2\\python\\plugins\\irods_qgis', 'C:\\Users\\Administrator\\.qgis2\\python\\plugins\\MetaSearch\\ext-libs', 'C:\\PROGRA~1\\QGISBR~1\\apps\\qgis\\python\\plugins\\fTools\\tools']

**Comment by demarcog** [comment]
hello
I would like to point out that my plugin is intended to work on vector
layers that is to say that you can clip polygon or line layers features. If
you meant to clip raster images using a vector mask you should use the
appropriate built-in function from Raster-->extraction-->clipper which has
nothing to do with my plugin.

Best regards

Giuseppe De Marco

2015-03-13 11:24 GMT+01:00 shetie Gatew mitiku <notifications@github.com>:

> clipper doesn't work any more
> I tried to clip raster image masking with vector data but the clipper
> gives the following message.Would you please help me. I'm doing in qgis
> 2.6.1
> An error has occured while executing Python code:
>
> Traceback (most recent call last):
> File
> "C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins\GdalTools\tools\extentSelector.py",
> line 114, in fillCoords
> self.blockSignals(True)
> RuntimeError: wrapped C/C++ object of type GdalToolsExtentSelector has
> been deleted
>
> Python version:
> 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
>
> QGIS version:
> 2.6.1-Brighton Brighton, e2a51df
>
> Python path:
> ['C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins\processing',
> 'C:/PROGRA~1/QGISBR~1/apps/qgis/./python',
> u'C:/Users/Administrator/.qgis2/python',
> u'C:/Users/Administrator/.qgis2/python/plugins',
> 'C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg',
> 'C:\Program Files (x86)\ArcGIS\bin',
> 'C:\PROGRA~1\QGISBR~1\bin\python27.zip',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\DLLs',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\plat-win',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\lib-tk', 'C:\PROGRA~1\QGISBR~1\bin'
> , 'C:\PROGRA~1\QGISBR~1\apps\Python27',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\PIL',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\win32',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\win32\lib',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\Pythonwin',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\six-1.3.0-py2.7.egg',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg',
> 'C:\PROGRA~1\QGISBR~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg',
> 'C: \Users\Administrator\.qgis2\python\plugins\FeatureGridCreator',
> 'C:\Users\Administrator\.qgis2\python\plugins\irods_qgis',
> 'C:\Users\Administrator\.qgis2\python\plugins\MetaSearch\ext-libs',
> 'C:\PROGRA~1\QGISBR~1\apps\qgis\python\plugins\fTools\tools']
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/demarcog/Clipper/issues/2#issuecomment-78904285>.
>



-- 
Dott. Agr. Giuseppe De Marco
RSPP settore ATECO 1
Cell./Mobile: +39 3935041115
Fax.: +39 07751850973
PEC: giuseppe.de_marco@epap.conafpec.it

**Comment by shetie** [comment]
Hello,I want to clip raster image with vector data mask and as I told you, the following pop up appeared. Now I installed 2.7.1 python but another pop up similar to the first appeared. Therefore, I couldn't able to clip my raster image with the vector polygon mask.I appreciate  your immediate help indeed. Best regards,
Shetie Gatew Mitiku (PhD student) 
Department of BiologyArba Minch UniversityShetiegatew@gmail.com;shetieg@yahoo.com+251-913-070305EthiopiaEarth and Environmental Science 
Katholic University of LeuvenBelgium

**Comment by demarcog** [comment]
Ok I understand. If you want to clip a raster image with a vector mask you
should use the clipper function from raster menu and not my plugin called
clipper which is under vector menu. I hope this will help you out.
Il 13/Mar/2015 13:28 "shetie Gatew mitiku" <notifications@github.com> ha
scritto:
